{% set name = "flowsaber" %}
{% set version = "0.1.3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flowsaber-{{ version }}.tar.gz
  sha256: 9dd54585dcceab1fa91f61b15cd9966d28b18523fc915902d396055fe070e78a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aiohttp
    - ariadne
    - cloudpickle
    - dask-core
    - distributed
    - dnspython
    - fire
    - makefun
    - motor
    - psutil
    - pydantic
    - python >={{ python_min }}
    - uvicorn

test:
  imports:
    - flowsaber
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/zhqu1148980644/flowsaber
  doc_url: https://flowsaber.github.io/flowsaber/
  summary: A dataflow based workflow framework
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
